### ISSUE TITLE
File-Upload through API of filehoster

### ISSUE THREAD

**Issue by markus-hinsche** [nicolas-fricke/transfair#14]
Costs of filehoster?

**Comment by nicolas-fricke** [comment]
We might use Dropbox for this.. Need to do more research

**Comment by briodf** [comment]
Don't know if it helps, but can solve the problem in short term. https://airdropper.com/ (File dropper directly linked with a dropbox)

**Comment by markus-hinsche** [comment]
dropbox insert file field can be inside the job/_form.html.erb

**Comment by nicolas-fricke** [comment]
Did we decide on Dropbox now? Can we close this ticket?
