### ISSUE TITLE
Integrate information we get from forms for clients and service partners

### ISSUE THREAD

**Issue by markus-hinsche** [nicolas-fricke/transfair#17]
maybe we could be man-in-the-middle for the google form

**Comment by nicolas-fricke** [comment]
Is this still relevant? Or do we just plan to build our own solution?

**Comment by briodf** [comment]
Don't really understand what it means, but we will need some forms (here are the ones we are using right now http://transfair.co/give-work/ http://transfair.co/form-page/)
