### ISSUE TITLE
Add gender to db 

### ISSUE THREAD

**Issue by briodf** [nicolas-fricke/transfair#34]
Following what I saw in Markus' commit (Fourth one: https://github.com/nicolas-fricke/transfair/commit/0af47609f1b63e6fa83f6d8236bbf5512bc275f6) , could it be a way to add gender in the db (for my curiosity)? : 

``` ruby
+class AddIsFemaleToServicePartner < ActiveRecord::Migration    
+  def change
+    add_column :service_partners, :is_female, :bool
+  end  
+end
```

**Comment by markus-hinsche** [comment]
yeah, thats how you could do it
the filename is also important, it needs to have the right timestamp, so that the migrations have the right order

**Comment by briodf** [comment]
Okey, could you correct it? The gender is something I forgot in our database shema.
