### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by markus-hinsche** [nicolas-fricke/transfair#36]
we use simple-form gem
in the moment validation is poorly styled -> this is improved by simple-form
validation means e.g. the error message when you have a form and didn't fill a mandatory field.

**Comment by markus-hinsche** [comment]
I implemented a nicer way for the client form. Should we use it for all (it's a gem called simple form)

**Comment by markus-hinsche** [comment]
maybe Francois can program which attributes can be in forms, cause it's so easy:)
https://github.com/plataformatec/simple_form/#twitter-bootstrap

**Comment by briodf** [comment]
When I write the forms, where do I have to save them on github?

**Comment by markus-hinsche** [comment]
you open the form, e.g. https://github.com/nicolas-fricke/transfair/blob/master/app/views/clients/_form.html.erb
then you write it with the syntax I used for the client but you do this for SP and Jobs too, e.g. https://github.com/nicolas-fricke/transfair/blob/master/app/views/service_partners/_form.html.erb
then you commit it

**Comment by markus-hinsche** [comment]
Can a datepicker still be displayed with simple-form?

**Comment by markus-hinsche** [comment]
yes its possible: because you can apply the same syntax of usual forms as well for simple-form files. The code for the label and the input field just look a bit crappy. 
Maybe we can build a custom-input:
https://github.com/plataformatec/simple_form/#custom-inputshttps://github.com/plataformatec/simple_form/#custom-inputs
