### ISSUE TITLE
The direct download link of the file stored in the DB should be stored in the database and be linked with a job

### ISSUE THREAD

**Issue by briodf** [nicolas-fricke/transfair#65]

**Comment by rtens** [comment]
So the good news is that the API supports this:
https://www.dropbox.com/developers/reference/api#shares

and the Ruby implementation as well:
https://www.dropbox.com/static/developers/dropbox-ruby-sdk-1.5-docs/classes/DropboxClient.html#M000020

It says in the API doc that the links expire waaaay in the future (e.g. 2030) and can be ignored but the Ruby doc states the opposite so I'm not a 100% on this. Not even dropbox-moderators are very certain: https://forums.dropbox.com/topic.php?id=66450#post-466382

Maybe it would be a better solution to store the file path. You could then create links on-demand. This would have other advantages as well e.g. getting other information about the file and even if the links don't expire no they might always change this in the future.
