### ISSUE TITLE
A service partner must have a reliability score 

### ISSUE THREAD

**Issue by briodf** [nicolas-fricke/transfair#70]
``` ruby
reliability_score = AVG(job.deadline_client - job_status(handed in).created)
```

(to be defined more properly)

**Comment by markus-hinsche** [comment]
we don't understand the formula. please use natural language for formular!

**Comment by briodf** [comment]
I am open for a more complex algorithm. It was just the average of the time before the deadline and when the job was handed in. 

The reliability score should encompass:

-the fact that they handed in their job in time
-should increase with the number of job they handed in in time
-should dramatically decrease when they miss a deadline (risk aversion)

nice to have:
-the fact that they respond to email (quickly)
